#!/usr/bin/env python3
"""
convert_sprite.py — Convert mascot image to C header for The Emu Pages

Reads the mascot WebP/PNG image, scales it to fit the boot screen,
and outputs src/mascot_data.h with XRGB8888 pixel data.

Usage:
    python3 tools/convert_sprite.py
"""

import os
import sys

try:
    from PIL import Image
except ImportError:
    print("ERROR: Pillow is required. Install with: pip3 install Pillow")
    sys.exit(1)

INPUT_FILE = os.path.join(os.path.dirname(__file__), "emuvr_mascot.webp")
OUTPUT_FILE = "src/mascot_data.h"
TARGET_HEIGHT = 160  # pixels — fits nicely above the loading bar

def main():
    print("Emu Pages Sprite Converter")
    print("==========================")

    img = Image.open(INPUT_FILE).convert("RGBA")
    print(f"Source: {img.size[0]}x{img.size[1]} RGBA")

    # Scale to target height, maintaining aspect ratio
    scale = TARGET_HEIGHT / img.size[1]
    new_w = int(img.size[0] * scale)
    new_h = TARGET_HEIGHT
    img = img.resize((new_w, new_h), Image.NEAREST)
    print(f"Scaled: {new_w}x{new_h}")

    # Convert to pixel array
    pixels = list(img.getdata())

    out = []
    out.append("/* AUTO-GENERATED by tools/convert_sprite.py -- DO NOT EDIT */")
    out.append("#ifndef MASCOT_DATA_H")
    out.append("#define MASCOT_DATA_H")
    out.append("")
    out.append(f"#define MASCOT_W {new_w}")
    out.append(f"#define MASCOT_H {new_h}")
    out.append("")
    out.append("/* ARGB8888: alpha in top byte, 0x00 = transparent */")
    out.append(f"static const uint32_t mascot_pixels[{new_w * new_h}] = {{")

    # Write pixels in rows for readability
    for y in range(new_h):
        row_start = y * new_w
        row_pixels = []
        for x in range(new_w):
            r, g, b, a = pixels[row_start + x]
            if a < 128:
                # Transparent
                row_pixels.append("0x00000000")
            else:
                # Opaque: store as 0xAARRGGBB
                val = (a << 24) | (r << 16) | (g << 8) | b
                row_pixels.append(f"0x{val:08X}")
        out.append("    " + ",".join(row_pixels) + ",")

    out.append("};")
    out.append("")
    out.append("#endif /* MASCOT_DATA_H */")

    header = "\n".join(out) + "\n"
    with open(OUTPUT_FILE, "w") as f:
        f.write(header)

    file_size = os.path.getsize(OUTPUT_FILE)
    print(f"Output: {OUTPUT_FILE} ({file_size // 1024}KB)")
    print(f"Done! {new_w}x{new_h} = {new_w * new_h} pixels")


if __name__ == "__main__":
    main()
